// livro-clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      });
    });
  };

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="container mt-4">
  <h1>Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="bg-dark text-white">Título</th>
        <th class="bg-dark text-white">Resumo</th>
        <th class="bg-dark text-white">Editora</th>
        <th class="bg-dark text-white">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          <div>{{ livro.titulo }}</div>
          <button
            class="btn btn-danger btn-sm mt-2"
            (click)="livro.codigo ? excluir(livro.codigo) : null"
          >
            Excluir
          </button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// livro-clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from "react";
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LinhaLivro = (props) => {
  const nomeEditora = controleEditora.getNomeEditora(props.livro.codEditora);
  return (
    <tr>
      <td>
        <div>{props.livro.titulo}</div>
        <button
          onClick={() => props.excluir(props.livro.codigo)}
          className="btn btn-danger mt-2"
        >
          Excluir
        </button>
      </td>
      <td>{props.livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {props.livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
};

const LivroLista = () => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    const fetchLivros = async () => {
      if (!carregado) {
        controleLivro.obterLivros().then((resultado) => {
          setLivros(resultado);
          setCarregado(true);
        });
      }
    };
    fetchLivros();
  }, [carregado]);

  const excluir = (codigo) => {
    controleLivro.excluir(codigo).then(() => {
      setCarregado(false);
    });
  };

  return (
    <main className="container mt-4">
      <h1>Catálogo de Livros</h1>
      <table className="table table-striped">
        <thead>
          <tr>
            <th className="bg-dark text-white">Título</th>
            <th className="bg-dark text-white">Resumo</th>
            <th className="bg-dark text-white">Editora</th>
            <th className="bg-dark text-white">Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => (
            <LinhaLivro key={index} livro={livro} excluir={excluir} />
          ))}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;
